
project_id = "gqluohyewtjcjbntjfym"
[api]
enabled = true
[auth]
enabled = true
[realtime]
enabled = true
[storage]
enabled = true
[functions]
[functions.send-contact-email]
verify_jwt = false
[functions.verify-payment]
verify_jwt = true
[functions.create-razorpay-order]
verify_jwt = true
