// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqluohyewtjcjbntjfym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbHVvaHlld3RqY2pibnRqZnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTI5NzEsImV4cCI6MjA1NTgyODk3MX0.TpZcJNSLvG6ClX6ys5XMH0-O5621SmYE5Cf1OZIzAoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);