name: Vite React CI/CD

on:
  push:
    branches:
      - main
      - 'feature/*'   # Optional: Include your feature branches if needed
  pull_request:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (use the version you require, e.g., 18.x)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code
      - name: Run ESLint
        run: npm run lint

      # Build the project
      - name: Build project
        run: npm run build

  preview:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (same version as before)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Preview the build
      - name: Preview build
        run: npm run preview
        env:
          VITE_PORT: 3000 # Optional: Specify your port or any other environment variable
